### ISSUE TITLE
Plugin "browser_detect" missing

### ISSUE THREAD

**Issue by Signum** [derf/Travel-Status-DE-DeutscheBahn#1]
When starting the web application I get…

    Plugin "browser_detect" missing, maybe you need to install it?

I could not find any Mojolicious plugin with that name.

**Comment by derf** [comment]
Hi!

Yeah, it's not packaged with Mojolicious. See https://metacpan.org/pod/Mojolicious::Plugin::BrowserDetect

I'll update the README of https://github.com/derf/db-fakedisplay to reflect this.
