### ISSUE TITLE
Conceptual improvements to handling opL and prodL

### ISSUE THREAD

**Issue by deingithub** [derf/Travel-Status-DE-DeutscheBahn#10]
Some, especially international, trains, change operators and type/number while en route. The way this currently seems to be handled by the library is that the first (or well, the `res.journey.prodX`th, but I haven't seen a number other than 0 there yet) set of operator and product are taken for the entire train, even if these get changed after one or two stops (in the case i noticed this, the *REX3 Znojmo–Wiener Neustadt* was consistently listed as the *Os 2241* it starts its journey in Czechia as).
With the current API, it's not possible to access any data past the first set of operator/product without very haphazardly looking for remarks like "Verkehrt ab hier als REX 2241 in Richtung Wiener Neustadt Hbf".
A possible API shape to improve this might be `$journey->at(stop on route)->{operator}`, `->{type}` and so on.

**Comment by derf** [comment]
9ef75520eeaf1a568650f7368782ac63b80c09b2 seems to be working nicely; closing this as completed.

**Comment by deingithub** [comment]
Thanks!
