### ISSUE TITLE
Product Mask doesn't really work as intended with ÖBB profile

### ISSUE THREAD

**Issue by deingithub** [derf/Travel-Status-DE-DeutscheBahn#11]
Sorry for another headache around the Austrians :p

The ÖBB profile has the bitmask `[qw[ice ice ice regio regio s bus ferry u tram ice ondemand ice]]`. The way the `mot_mask` function is written leads to the "ICE" product mask only containing the last mention of it in the array and overwriting the earlier ones without including them into the mask: 
https://github.com/derf/Travel-Status-DE-DeutscheBahn/blob/aebdbb0d3f0521503ce46ff679ad2eb822503f0d/lib/Travel/Status/DE/HAFAS.pm#L510-L513 

The result is that when requesting with a `-m ice` filter you only get regiojet departures (mask `1000000000000`/4096) instead of regiojet, ec/ic and rj/rjx/ice departures (mask `1000000000101`/4101):
![image](https://github.com/derf/Travel-Status-DE-DeutscheBahn/assets/46252311/a3f73dfd-160b-4cf2-9df5-9f7ab7611c9b)

Note also that the way the SCOTTY webapp currently renders its product filter has slightly more differentiation:
![image](https://github.com/derf/Travel-Status-DE-DeutscheBahn/assets/46252311/f5374714-a9ad-4be7-835e-fe604ee83e4e)

- Fernreisezüge *long distance trains* (`1000000000101` = `100000000000` Regiojet + `100` IC/EC + `1` RJ/RJX/ICE)
- Nachtreise- & Schnellzüge *night trains and rapid trains* (`1000` D/NJ/EN)
- Regionale Reisezüge *regional trains* (`10000` R, REX, CJX, …)
- S-Bahnen *suburban trains* (`100000`)
- U-Bahnen *underground* (`100000000`)
- Straßenbahnen *trams* (`1000000000`)
- Busse *busses* (`1000000`)
- Schifffahrtsverkehre *maritime traffic* (`10000000`)
- Sonstige Verkehre *other traffic* (`100000000000`)
- Schienenersatzverkehre *rail replacemen service* (`10`)

The simplest fix for this would be just giving each category its name and letting API users reconstruct the long distance category as presented on SCOTTY on their own, combining them into one category as the current implementation intends to might also be an option, but would be more complicated and require a rewrite of the `mot_mask` function.

**Comment by derf** [comment]
Thanks for the (as always) detailed report!

For now I'll leave it at a simple update of the productbits definition. I think in the long run I'll, at the very least, add backend-specific help texts that explain what the abbreviations inside the mot / productbits list mean.  I already know which GitHub issue I can rely on for the ÖBB part :)

**Comment by deingithub** [comment]
Thanks for the quick fix, the reports are fun to write ^^
